version: '3.8'

services:
  catboard-db:
    image: mysql:8.0.32
    container_name: catboard-db
    hostname: catboard-db
    environment:
      - MYSQL_ROOT_PASSWORD=no8Ishei
      - MYSQL_USER=catboard
      - MYSQL_PASSWORD=Ook4au5a
      - MYSQL_DATABASE=catboard
    volumes:
      - $PWD/docker/config/mysql.d/:/etc/mysql/conf.d/:ro
      - catboard_db_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  catboard_db_data:
